packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  "@base-ui/react": ^1.5.0
  prettier: ^3.8.3
  "@ianvs/prettier-plugin-sort-imports": ^4.7.1
  prettier-plugin-tailwindcss: ^0.8.0
  html-minifier-next: ^6.2.8
  satteri: ^0.8.0
  yaml: ^2.9.0

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

allowBuilds:
  esbuild: true
  msw: true
